<b><font size="6">Predictive Modelling Pipeline Template</font></b><br><br>

In this notebook we present to you the main steps you should follow throughout your project.


<b> Important: The numbered sections and subsections are merely indicative of some of the steps you should pay attention to in your project. <br>You are not required to strictly follow this order or to execute everything in separate cells.</b>
    
<img src="image/process_ML.png" style="height:70px">

In [98]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.experimental import enable_iterative_imputer

import warnings
warnings.filterwarnings('ignore')

<a class="anchor" id="">

# 1. Import data (Data Integration)

</a>

<img src="image/step1.png" style="height:60px">

In [99]:
# Load the data in a simple way
obesity_train_raw = pd.read_csv('../data/obesity_train.csv')
obesity_test_raw = pd.read_csv('../data/obesity_test.csv')

In [100]:
obesity_train_raw.head(10)

,id,age,alcohol_freq,caloric_freq,devices_perday,eat_between_meals,gender,height,marrital_status,meals_perday,...,parent_overweight,physical_activity_perweek,region,siblings,smoke,transportation,veggies_freq,water_daily,weight,obese_level
0,1,21.0,Never,no,up to 5,Sometimes,Female,1.62,NaN,3.0,...,yes,NaN,LatAm,3.0,no,Public,Sometimes,1 to 2,64.0,Normal_Weight
1,2,23.0,Frequently,no,up to 5,Sometimes,Male,1.80,NaN,3.0,...,yes,3 to 4,LatAm,0.0,no,Public,Sometimes,1 to 2,77.0,Normal_Weight
2,3,NaN,Frequently,no,up to 2,Sometimes,Male,1.80,NaN,3.0,...,no,3 to 4,LatAm,2.0,no,Walk,Always,1 to 2,87.0,Overweight_Level_I
3,4,22.0,Sometimes,no,up to 2,Sometimes,Male,1.78,NaN,1.0,...,no,NaN,LatAm,3.0,no,Public,Sometimes,1 to 2,90.0,Overweight_Level_II
4,5,22.0,Sometimes,no,up to 2,Sometimes,Male,1.64,NaN,3.0,...,no,5 or more,LatAm,3.0,no,Public,Sometimes,1 to 2,53.0,Normal_Weight
5,6,24.0,Frequently,yes,up to 5,Sometimes,Male,1.78,NaN,3.0,...,yes,1 to 2,LatAm,2.0,no,Public,Always,1 to 2,64.0,Normal_Weight
6,7,21.0,Sometimes,yes,up to 5,Frequently,Female,1.72,NaN,3.0,...,yes,3 to 4,NaN,2.0,no,Public,Sometimes,1 to 2,80.0,Overweight_Level_II
7,8,22.0,Sometimes,no,up to 2,Sometimes,Male,1.65,NaN,3.0,...,no,3 to 4,LatAm,1.0,no,Public,Always,more than 2,56.0,Normal_Weight
8,9,41.0,Frequently,yes,up to 5,Sometimes,Male,1.80,NaN,3.0,...,no,3 to 4,LatAm,0.0,no,Car,Sometimes,1 to 2,99.0,Obesity_Type_I
9,10,27.0,Sometimes,yes,up to 2,Sometimes,Male,1.93,NaN,1.0,...,yes,1 to 2,LatAm,2.0,no,Public,Sometimes,less than 1,102.0,Overweight_Level_II

In [101]:
obesity_test_raw.head(10)

,id,age,alcohol_freq,caloric_freq,devices_perday,eat_between_meals,gender,height,marrital_status,meals_perday,monitor_calories,parent_overweight,physical_activity_perweek,region,siblings,smoke,transportation,veggies_freq,water_daily,weight
0,1612,21.0,Sometimes,no,up to 2,Sometimes,Female,1.52,NaN,3.0,yes,yes,5 or more,LatAm,3.0,yes,Public,Always,more than 2,56.0
1,1613,29.0,Sometimes,yes,up to 2,Sometimes,Male,1.62,NaN,3.0,no,no,NaN,LatAm,3.0,no,Car,Sometimes,1 to 2,53.0
2,1614,23.0,Sometimes,NaN,up to 2,Sometimes,Female,1.50,NaN,3.0,no,yes,1 to 2,LatAm,2.0,no,Motorbike,Always,1 to 2,NaN
3,1615,22.0,Never,yes,up to 5,Sometimes,Male,1.72,NaN,3.0,no,yes,1 to 2,LatAm,1.0,no,Public,Sometimes,1 to 2,68.0
4,1616,26.0,Sometimes,yes,more than 5,Frequently,Male,1.85,NaN,3.0,no,yes,3 to 4,LatAm,1.0,no,Public,Always,more than 2,105.0
5,1617,23.0,Sometimes,yes,up to 5,Sometimes,Male,1.77,NaN,1.0,no,yes,1 to 2,LatAm,2.0,no,Public,Always,less than 1,60.0
6,1618,22.0,Sometimes,no,up to 5,Always,Female,1.70,NaN,3.0,yes,yes,3 to 4,LatAm,1.0,no,Public,Always,1 to 2,NaN
7,1619,29.0,Never,yes,up to 2,Sometimes,Female,1.53,NaN,1.0,no,no,NaN,LatAm,0.0,no,Car,Sometimes,1 to 2,78.0
8,1620,30.0,Never,yes,up to 2,Frequently,Female,1.71,NaN,4.0,no,yes,NaN,LatAm,0.0,yes,Car,Always,less than 1,82.0
9,1621,23.0,Sometimes,yes,up to 5,Frequently,Female,1.60,NaN,4.0,no,no,3 to 4,LatAm,3.0,no,Car,Sometimes,1 to 2,52.0

<a class="anchor" id="">

# 2. Explore data (Data access, exploration and understanding)

</a>

<img src="image/step2.png" style="height:60px">

Remember, this step is very important as it is at this stage that you will really look into the data that you have. Generally speaking, if you do well at this stage, the following stages will be very smooth.

Moreover, you should also take the time to find meaningful patterns on the data: what interesting relationships can be found between the variables and how can that knowledge be inform your future decisions.

In [102]:
# Display information about the training dataset
obesity_train_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1611 entries, 0 to 1610
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1611 non-null   int64
 1   age                        1545 non-null   float64
 2   alcohol_freq               1575 non-null   object
 3   caloric_freq               1591 non-null   object
 4   devices_perday             1589 non-null   object
 5   eat_between_meals          1552 non-null   object
 6   gender                     1591 non-null   object
 7   height                     1597 non-null   float64
 8   marrital_status            0 non-null      float64
 9   meals_perday               1602 non-null   float64
 10  monitor_calories           1572 non-null   object
 11  parent_overweight          1591 non-null   object
 12  physical_activity_perweek  1046 non-null   object
 13  region                     1544 non-null   object
 14  siblings                   1599 non-null   float64
 15  smoke                      1599 non-null   object
 16  transportation             1571 non-null   object
 17  veggies_freq               1585 non-null   object
 18  water_daily                1577 non-null   object
 19  weight                     1558 non-null   float64
 20  obese_level                1611 non-null   object
dtypes: float64(6), int64(1), object(14)
memory usage: 264.4+ KB

In [103]:
obesity_train_raw.age.sort_values(ascending=False).head(3)

1013    88.0
100     61.0
882     55.0
Name: age, dtype: float64

<a class="anchor" id="">

# 3. Modify data (Data preparation)

</a>

<img src="image/step3.png" style="height:60px">

Use this section to apply transformations to your dataset.

Remember that your decisions at this step should be exclusively informed by your **training data**. While you will need to split your data between training and validation, how that split will be made and how to apply the approppriate transformations will depend on the type of model assessment solution you select for your project (each has its own set of advantages and disadvantages that you need to consider). **Please find a list of possible methods for model assessment below**:

1. **Holdout method**
2. **Repeated Holdout method**
3. **Cross-Validation**

__Note:__ Instead of creating different sections for the treatment of training and validation data, you can make the transformations in the same cell. There is no need to create a specific section for that.

### 3.1. Data Preparation

In [104]:
# Drop the 'marrital_status' and 'region' columns from the dataset
obesity_train = obesity_train_raw.drop(columns=['marrital_status', 'region'])
obesity_test = obesity_test_raw.drop(columns=['marrital_status', 'region'])

In [105]:
obesity_train.set_index('id', inplace=True)
obesity_test.set_index('id', inplace=True)
obesity_train

,age,alcohol_freq,caloric_freq,devices_perday,eat_between_meals,gender,height,meals_perday,monitor_calories,parent_overweight,physical_activity_perweek,siblings,smoke,transportation,veggies_freq,water_daily,weight,obese_level
id,,,,,,,,,,,,,,,,,,
1,21.0,Never,no,up to 5,Sometimes,Female,1.62,3.0,no,yes,NaN,3.0,no,Public,Sometimes,1 to 2,64.0,Normal_Weight
2,23.0,Frequently,no,up to 5,Sometimes,Male,1.80,3.0,no,yes,3 to 4,0.0,no,Public,Sometimes,1 to 2,77.0,Normal_Weight
3,NaN,Frequently,no,up to 2,Sometimes,Male,1.80,3.0,no,no,3 to 4,2.0,no,Walk,Always,1 to 2,87.0,Overweight_Level_I
4,22.0,Sometimes,no,up to 2,Sometimes,Male,1.78,1.0,no,no,NaN,3.0,no,Public,Sometimes,1 to 2,90.0,Overweight_Level_II
5,22.0,Sometimes,no,up to 2,Sometimes,Male,1.64,3.0,no,no,5 or more,3.0,no,Public,Sometimes,1 to 2,53.0,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1607,21.0,Sometimes,NaN,up to 5,Sometimes,Female,1.73,3.0,no,yes,3 to 4,1.0,no,Public,Always,1 to 2,131.0,Obesity_Type_III
1608,22.0,Sometimes,yes,up to 5,Sometimes,Female,1.75,3.0,no,yes,1 to 2,0.0,no,NaN,Always,1 to 2,134.0,Obesity_Type_III
1609,23.0,Sometimes,yes,up to 5,Sometimes,Female,1.75,3.0,no,yes,1 to 2,0.0,no,Public,Always,1 to 2,134.0,Obesity_Type_III
1610,24.0,Sometimes,yes,up to 5,Sometimes,Female,1.74,3.0,no,yes,1 to 2,0.0,no,Public,Always,more than 2,133.0,Obesity_Type_III
1611,24.0,Sometimes,yes,up to 5,Sometimes,Female,1.74,3.0,no,yes,1 to 2,0.0,no,Public,Always,more than 2,133.0,Obesity_Type_III

In [106]:
# Selecting outliers for which the age is out of scope. Or the weight classification is suspiciously low for the value given
outliers = obesity_train[
    ((obesity_train['age'] < 16) & ~(obesity_train['age'].isna())) |
    ((obesity_train['age'] > 56) & ~(obesity_train['age'].isna())) |
    ((obesity_train['weight'] > 167) & ~(obesity_train['weight'].isna()))
]
obesity_train.drop(outliers.index, inplace=True)
obesity_train.reset_index(drop=True, inplace=True)

In [107]:
obesity_train.shape # Shape adds up to our expectation (6 rows deleted) 1611 -> 1605 rows

(1605, 18)

# Preprocessing Data
Our autonomous module does everything, which comprehends:
- Imputing missing values with various algorithms
- Encoding qualitative variables
- Scaling and transforming quantitative variables
- Feature engineering

In [126]:
from data_preprocesser import preprocesser

my_preprocesser = preprocesser()

preprocessed_train, preprocessed_test = my_preprocesser.run(obesity_train.drop("obese_level", axis=1), obesity_test)

Preprocesser loaded

### 3.4. Feature Selection

In [ ]:
preprocessed_test.head(3)

,age,height,siblings,weight,alcohol_freq_encoded,caloric_freq_encoded,devices_perday_encoded,meals_perday_encoded,monitor_calories_encoded,parent_overweight_encoded,physical_activity_perweek_encoded,transportation_encoded,veggies_freq_encoded,water_daily_encoded,bmi_class_encoded,eat_between_meals_encoded,gender_1.0,smoke_1.0
id,,,,,,,,,,,,,,,,,,
1612,-0.537743,-1.945856,3.0,-1.205275,3.0,0.0,1.0,2.0,1.0,1.0,2.0,3.0,0.0,2.0,0.0,3.0,0.0,1.0
1613,0.775721,-0.887717,3.0,-1.322349,3.0,1.0,1.0,2.0,0.0,0.0,3.0,1.0,2.0,0.0,0.0,3.0,1.0,0.0
1614,-0.209377,-2.157484,2.0,-0.838445,3.0,1.0,1.0,2.0,0.0,1.0,0.0,2.0,0.0,0.0,2.0,3.0,0.0,0.0

In [127]:
preprocessed_train['obese_level'] = obesity_train['obese_level']

label_encoder = LabelEncoder()
preprocessed_train['obese_level'] = label_encoder.fit_transform(preprocessed_train['obese_level'])
preprocessed_train

,age,height,siblings,weight,alcohol_freq_encoded,caloric_freq_encoded,devices_perday_encoded,meals_perday_encoded,monitor_calories_encoded,parent_overweight_encoded,physical_activity_perweek_encoded,transportation_encoded,veggies_freq_encoded,water_daily_encoded,bmi_class_encoded,eat_between_meals_encoded,gender_1.0,smoke_1.0,obese_level
0,-0.537743,-0.887717,3.0,-0.893079,2.0,0.0,2.0,2.0,0.0,1.0,3.0,3.0,2.0,0.0,0.0,3.0,0.0,0.0,1
1,-0.209377,1.016935,0.0,-0.385761,1.0,0.0,2.0,2.0,0.0,1.0,1.0,3.0,2.0,0.0,0.0,3.0,1.0,0.0,1
2,-0.603416,1.016935,2.0,0.004484,1.0,0.0,1.0,2.0,0.0,0.0,1.0,4.0,0.0,0.0,2.0,3.0,1.0,0.0,5
3,-0.373560,0.805307,3.0,0.121557,3.0,0.0,1.0,0.0,0.0,0.0,3.0,3.0,2.0,0.0,2.0,3.0,1.0,0.0,6
4,-0.373560,-0.676089,3.0,-1.322349,3.0,0.0,1.0,2.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,3.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1600,-0.537743,0.276237,1.0,1.721561,3.0,0.0,2.0,2.0,0.0,1.0,1.0,3.0,0.0,0.0,1.0,3.0,0.0,0.0,4
1601,-0.373560,0.487865,0.0,1.838634,3.0,1.0,2.0,2.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,3.0,0.0,0.0,4
1602,-0.209377,0.487865,0.0,1.838634,3.0,1.0,2.0,2.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,3.0,0.0,0.0,4
1603,-0.045194,0.382051,0.0,1.799610,3.0,1.0,2.0,2.0,0.0,1.0,0.0,3.0,0.0,2.0,1.0,3.0,0.0,0.0,4
1604,-0.045194,0.382051,0.0,1.799610,3.0,1.0,2.0,2.0,0.0,1.0,0.0,3.0,0.0,2.0,1.0,3.0,0.0,0.0,4

In [137]:
X_train, X_val, y_train, y_val = train_test_split(preprocessed_train, preprocessed_train['obese_level'], test_size=0.3, random_state=42)

In [140]:
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier


tree = RandomForestClassifier(random_state=42)

rf = tree.fit(X_train, y_train) # Fit

print(f"Train score: {rf.score(X_train, y_train)}")

print(classification_report(y_val, rf.predict(X_val)))

Train score: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      0.99      0.99        72
           2       0.99      1.00      0.99        76
           3       1.00      1.00      1.00        78
           4       1.00      1.00      1.00        61
           5       1.00      1.00      1.00        65
           6       1.00      1.00      1.00        61

    accuracy                           1.00       482
   macro avg       1.00      1.00      1.00       482
weighted avg       1.00      1.00      1.00       482

In [ ]:
importances = tree.feature_importances_

importances_df = pd.DataFrame(importances, index=preprocessed_train.columns, columns=['importance'])
importances_df = importances_df.sort_values('importance', ascending=False)
importances_df

<a class="anchor" id="">

# 4 & 5. Model & Assess (Modelling and Assessment)

</a>

<img src="image/step4.png" style="height:60px">

### 4.1. Model Selection

In this section you should take the time to train different predictive algorithms with the data that got to this stage and **use the approppriate model assessment metrics to decide which model you think is the best to address your problem**.

**You are expected to present on your report the model performances of the different algorithms that you tested and discuss what informed your choice for a specific algorithm**

### 4.2. Model Optimization

After selecting the best algorithm (set of algorithms), you can try to optimize the performance of your model by fiddling with the algorithms' hyper-parameters and select the options that result on the best overall performance.

Possible ways of doing this can be through:
1. [GridSearch](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)
2. [RandomSearch](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html)

**While you are not required to show the results of all combinations of hyperparameters that you tried, you should at least discuss the what were the possible combinations used and which of them resulted in your best performance**

<a class="anchor" id="">

# 5. Deploy

</a>

<img src="image/step5.png" style="height:60px">

### 5.0 Training a final model

You used the previous steps of modelling and assessment to determine what would be best strategies when it comes to preprocessing, scaling, feature selection, algorithm and hyper-parameters you could find.

**By this stage, all of those choices were already made**. For that reason, a split between training and validation is no longer necessary. **A good practice** would be to take the initial data and train a final model with all of the labeled data that you have available.

**Everything is figured by this stage**, so, on a first level all you need to do is replicate the exact preprocessing, scaling and feature selection decisions you made before.<br>
When it comes to the final model, all you have to do is creeate a new instance of your best algorithm with the best parameters that you uncovered (no need to try all algorithms and hyper-parameters again).

### 5.1. Import and Transform your test data

Remember, the test data does not have the `outcome` variable.

### 5.2. Obtain Predictions on the test data from your final model

### 5.3. Create a Dataframe containing the index of each row and its intended prediction and export it to a csv file

Submit the csv file to Kaggle to obtain the model performance of your model on the test data.